### ISSUE TITLE
HitMan exception after use of SCENCO tool

### ISSUE THREAD

**Issue by workcraft-lp** [workcraft-lp/workcraft-test#31]
To reproduce open the attached file and move the mouse over the nodes. The following exception is thrown:

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at org.workcraft.plugins.cpog.VisualScenario.hitTestInLocalSpace(VisualScenario.java:269)
        at org.workcraft.dom.visual.VisualTransformableNode.hitTest(VisualTransformableNode.java:163)
        at org.workcraft.dom.visual.HitMan.isBranchHit(HitMan.java:94)
        at org.workcraft.dom.visual.HitMan.hitBranch(HitMan.java:131)
        at org.workcraft.dom.visual.HitMan.hitFirst(HitMan.java:121)
        at org.workcraft.dom.visual.HitMan.hitFirstChild(HitMan.java:146)
        at org.workcraft.dom.visual.HitMan.hitTestForSelection(HitMan.java:203)
        at org.workcraft.dom.visual.HitMan.hitTestForSelection(HitMan.java:277)
        at org.workcraft.gui.graph.tools.SelectionTool.updateState(SelectionTool.java:245)
        at org.workcraft.gui.graph.tools.SelectionTool.mouseMoved(SelectionTool.java:342)
        at org.workcraft.gui.graph.GraphEditorPanelMouseListener.mouseMoved(GraphEditorPanelMouseListener.java:75)
        at java.awt.Component.processMouseMotionEvent(Unknown Source)
        at javax.swing.JComponent.processMouseMotionEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$200(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

------------------------------------
This issue was imported from Launchpad bug.

 * date created: 2014-08-01T22:23:25Z
 * date closed: 2014-08-04T14:15:58Z
 * owner: danilovesky
 * assignee: danilovesky
 * the launchpad url was https://bugs.launchpad.net/bugs/1351504

**Comment by workcraft-lp** [comment]
*danilovesky at 2014-08-01T22:23:25Z:*
