### ISSUE TITLE
Circuit copy-paste breaks after STG conversion

### ISSUE THREAD

**Issue by workcraft-lp** [workcraft-lp/workcraft-test#37]
In complex circuit files (like the one attached), after conversion to STG the copy-paste gets broken.

It may be related to the fact that circuit stores some elements of STG.

------------------------------------
This issue was imported from Launchpad bug.

 * date created: 2014-11-12T11:20:16Z
 * owner: danilovesky
 * assignee: danilovesky
 * the launchpad url was https://bugs.launchpad.net/bugs/1391836

**Comment by workcraft-lp** [comment]
*danilovesky at 2014-11-12T11:20:16Z:*

**Comment by workcraft-lp** [comment]
*danilovesky at 2014-11-12T12:39:02Z:*

Select input port a, the outgoing arc and the joint it is connected to. Copy it into the clipboard. Try to paste - an exception is issued:

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.workcraft.dom.NodeContextTracker.nodeAdded(NodeContextTracker.java:78)
	at org.workcraft.dom.NodeContextTracker.handleEvent(NodeContextTracker.java:139)
	at org.workcraft.observation.HierarchySupervisor.notify(HierarchySupervisor.java:77)
	at org.workcraft.observation.ObservableHierarchyImpl.sendNotification(ObservableHierarchyImpl.java:43)
	at org.workcraft.dom.AbstractGroup.reparent(AbstractGroup.java:145)
	at org.workcraft.dom.math.MathGroup.reparent(MathGroup.java:92)
	at org.workcraft.dom.math.AbstractMathModel.setNamespaceRecursively(AbstractMathModel.java:76)
	at org.workcraft.dom.math.AbstractMathModel.reparent(AbstractMathModel.java:107)
	at org.workcraft.dom.visual.AbstractVisualModel.reparent(AbstractVisualModel.java:528)
	at org.workcraft.Framework.load(Framework.java:685)
	at org.workcraft.workspace.WorkspaceEntry.paste(WorkspaceEntry.java:361)
	at org.workcraft.gui.MainWindow.paste(MainWindow.java:1245)
	at org.workcraft.gui.MainWindowActions$16.run(MainWindowActions.java:161)
	at org.workcraft.gui.MainWindow$1.actionPerformed(MainWindow.java:117)
	at org.workcraft.gui.actions.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:58)
	at org.workcraft.gui.actions.ActionMenuItem.access$0(ActionMenuItem.java:55)
	at org.workcraft.gui.actions.ActionMenuItem$ActionForwarder.actionPerformed(ActionMenuItem.java:34)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:356)
	at javax.swing.plaf.basic.BasicMenuItemUI$Actions.actionPerformed(BasicMenuItemUI.java:802)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1662)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2878)
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:689)
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:697)
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(JMenuBar.java:697)
	at javax.swing.JMenuBar.processKeyBinding(JMenuBar.java:668)
	at javax.swing.KeyboardManager.fireBinding(KeyboardManager.java:307)
	at javax.swing.KeyboardManager.fireKeyboardAction(KeyboardManager.java:293)
	at javax.swing.JComponent.processKeyBindingsForAllComponents(JComponent.java:2970)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2962)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2841)
	at java.awt.Component.processEvent(Component.java:6293)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4872)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1887)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:762)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1027)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:899)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:727)
	at java.awt.Component.dispatchEventImpl(Component.java:4742)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:708)
	at java.awt.EventQueue$4.run(EventQueue.java:706)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by workcraft-lp** [comment]
*danilovesky at 2015-02-17T13:12:15Z:*

Looks like the attached file was generated by a buggy version of Workcraft - one of the Joint nodes does not have correct xml.
