### ISSUE TITLE
In pages the copy-paste does not work in the circuit plugin

### ISSUE THREAD

**Issue by workcraft-lp** [workcraft-lp/workcraft-test#64]
- create from circuit component, define some formula for it (an inverter, for instance)
- copy it to get the exception:

Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: org.workcraft.exceptions.DeserialisationException: org.workcraft.plugins.cpog.optimisation.javacc.ParseException: Undefined variable: 'var_'
	at org.workcraft.Framework.load(Framework.java:661)
	at org.workcraft.workspace.WorkspaceEntry.cancelMemento(WorkspaceEntry.java:212)
	at org.workcraft.workspace.WorkspaceEntry.copy(WorkspaceEntry.java:327)
	at org.workcraft.gui.MainWindow.copy(MainWindow.java:1203)
	at org.workcraft.gui.MainWindowActions$15.run(MainWindowActions.java:154)
	at org.workcraft.gui.MainWindow$1.actionPerformed(MainWindow.java:108)
	at org.workcraft.gui.actions.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:58)
	at org.workcraft.gui.actions.ActionMenuItem.access$0(ActionMenuItem.java:55)
	at org.workcraft.gui.actions.ActionMenuItem$ActionForwarder.actionPerformed(ActionMenuItem.java:34)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Actions.actionPerformed(Unknown Source)
	at javax.swing.SwingUtilities.notifyAction(Unknown Source)
	at javax.swing.JComponent.processKeyBinding(Unknown Source)
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(Unknown Source)
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(Unknown Source)
	at javax.swing.JMenuBar.processBindingForKeyStrokeRecursive(Unknown Source)
	at javax.swing.JMenuBar.processKeyBinding(Unknown Source)
	at javax.swing.KeyboardManager.fireBinding(Unknown Source)
	at javax.swing.KeyboardManager.fireKeyboardAction(Unknown Source)
	at javax.swing.JComponent.processKeyBindingsForAllComponents(Unknown Source)
	at javax.swing.JComponent.processKeyBindings(Unknown Source)
	at javax.swing.JComponent.processKeyEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.KeyboardFocusManager.redispatchEvent(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(Unknown Source)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$000(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: org.workcraft.exceptions.DeserialisationException: org.workcraft.plugins.cpog.optimisation.javacc.ParseException: Undefined variable: 'var_'
	at org.workcraft.plugins.cpog.serialisation.BooleanFunctionDeserialiser.readFormulaFromAttribute(BooleanFunctionDeserialiser.java:69)
	at org.workcraft.plugins.circuit.serialisation.FunctionDeserialiser.finaliseInstance(FunctionDeserialiser.java:55)
	at org.workcraft.serialisation.xml.DefaultNodeDeserialiser.doFinalisation(DefaultNodeDeserialiser.java:235)
	at org.workcraft.serialisation.xml.DefaultNodeDeserialiser.finaliseInstance(DefaultNodeDeserialiser.java:251)
	at org.workcraft.serialisation.xml.XMLDeserialisationManager.finaliseInstance(XMLDeserialisationManager.java:143)
	at org.workcraft.serialisation.xml.XMLDeserialisationManager.finaliseInstances(XMLDeserialisationManager.java:131)
	at org.workcraft.plugins.serialisation.XMLModelDeserialiser.deserialise(XMLModelDeserialiser.java:68)
	at org.workcraft.Framework.load(Framework.java:625)
	at org.workcraft.Framework.load(Framework.java:659)
	... 58 more
Caused by: org.workcraft.plugins.cpog.optimisation.javacc.ParseException: Undefined variable: 'var_'
	at org.workcraft.plugins.cpog.optimisation.javacc.BooleanParser.var(BooleanParser.java:27)
	at org.workcraft.plugins.cpog.optimisation.javacc.BooleanParser.literal(BooleanParser.java:251)
	at org.workcraft.plugins.cpog.optimisation.javacc.BooleanParser.andOp(BooleanParser.java:227)
	at org.workcraft.plugins.cpog.optimisation.javacc.BooleanParser.xorOp(BooleanParser.java:192)
	at org.workcraft.plugins.cpog.optimisation.javacc.BooleanParser.orOp(BooleanParser.java:170)
	at org.workcraft.plugins.cpog.optimisation.javacc.BooleanParser.implyOp(BooleanParser.java:148)
	at org.workcraft.plugins.cpog.optimisation.javacc.BooleanParser.neqOp(BooleanParser.java:130)
	at org.workcraft.plugins.cpog.optimisation.javacc.BooleanParser.eqOp(BooleanParser.java:108)
	at org.workcraft.plugins.cpog.optimisation.javacc.BooleanParser.formula(BooleanParser.java:86)
	at org.workcraft.plugins.cpog.optimisation.javacc.BooleanParser.parse(BooleanParser.java:61)
	at org.workcraft.plugins.cpog.serialisation.BooleanFunctionDeserialiser.readFormulaFromAttribute(BooleanFunctionDeserialiser.java:67)
	... 66 more

------------------------------------
This issue was imported from Launchpad bug.

 * date created: 2014-06-07T10:08:17Z
 * date closed: 2014-06-23T08:22:01Z
 * owner: sgaflv
 * assignee: sgaflv
 * the launchpad url was https://bugs.launchpad.net/bugs/1327520

**Comment by workcraft-lp** [comment]
*sgaflv at 2014-06-07T10:10:17Z:*

A significant change is needed in the way the variables inside the components are stored.
Now the circuit component needs to be a namespace provider for the input and output contacts inside it.
